sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc

install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck . --no-color -quiet -only "011"

after_script: 
file_type=
if [ -n "$tag" ]; then
    if [[ "${tag,,}" == *"alpha"* ]]; then
        file_type=alpha
    elif [[ "${tag,,}" == *"beta"* ]]; then
    file_type=beta
    else
        file_type=release
    fi
else
    echo "Found no tag, exiting."
    exit 0
fi
/curl -s [url]https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh[/url] | bash

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  apt: true
  directories:
    - $HOME/.luarocks
 
branches:
  only:
  - ^r\d+(-(alpha|beta))?(-\d+)?$