sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks
    - pandoc
	
install:
  - eval $(luarocks path --bin)
  - luarocks install --local luacheck

script: /home/travis/.luarocks/bin/luacheck . --no-color -quiet -only "011"

after_script: /curl -s [url]https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh[/url] | bash

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  apt: true
  directories:
    - $HOME/.luarocks
 
branches:
  only:
  - ^r\d+(-(alpha|beta))?(-\d+)?$